### ISSUE TITLE
elevate euler_60 into its own cargo package (making this project a workspace with multiple package)

### ISSUE THREAD

**Issue by tribbloid** [3rl-io/headset-utils#1]
I expect the euler_60 service to become more complex in the future, should it have its own package?

this will also enable more complex features to be enabled gradually, without introducing unnecessary dependencies. E.g, the current connection uses thread for async IO, but a new package can be introduced that uses tokio for the same purpose. Maybe it is easier to lay down the foundation early for future extensions?

**Comment by kkota1** [comment]
For spidgets we’ll do these as microservices to start and may package them when there’s 3+ that are needed

If your strategy will allow euler_60 to still be spawned independently, sounds good. Otherwise, please use a name like euler_60_2 so we can compare and decide later
